"""Sea Star Studio — the combo experience.

One submission → three deliverables (rhyme + voiced audio + coloring
page) bound together as a printable keepsake. Reuses every safety
helper, cache table, and storage path from penpals_router and
coloring_router, so it ships at near-zero incremental cost on
already-seen prompts.

Pipeline:
  1.  Sanitize + safety-check the letter (PII + kindness filter).
  2.  Rate-limit (default 3 keepsakes / day / visitor — separate from
      penpals + coloring so kids can use all three).
  3.  ONE Gemini Flash call returns both:
        - reply_text     (4 rhyming couplets, kid-safe, signed off)
        - scene_prompt   (5–12 word phrase describing what to draw)
      Parsed from a structured `RHYME: ... SCENE: ...` template.
  4.  Reuse the existing penpals cache for the rhyme + ElevenLabs audio.
  5.  Reuse the existing coloring cache for the scene PNG, generated by
      Gemini Nano Banana.
  6.  Persist the keepsake in db.sea_star_keepsakes (admin can soft-delete).
"""
from __future__ import annotations

import base64
import hashlib
import logging
import os
import re
import uuid
from typing import Optional

from fastapi import APIRouter, Depends, HTTPException
from pydantic import BaseModel, Field

from penpals_router import (
    sanitize_letter,
    contains_banned,
    _today_key,
    _now_iso,
    _synthesize_audio,
    _fallback_reply,
    _expected_audio_fragment,
)
from coloring_router import COLORING_DIR, _system_prompt as coloring_system_prompt, _is_blocked

logger = logging.getLogger("seastar-studio")


class StudioBody(BaseModel):
    character_slug: str
    letter: str = Field(min_length=2, max_length=400)
    visitor_id: str = Field(min_length=8, max_length=64)
    child_name: Optional[str] = ""


def _studio_system_prompt(ch: dict) -> str:
    name = ch.get("name", "Friend")
    role = ch.get("role", "")
    wave = (ch.get("wave_value") or "").upper()
    wave_lookup = {"W": "Welcome curiosity", "A": "Act with kindness", "V": "Value teamwork", "E": "Encourage others"}
    wave_phrase = wave_lookup.get(wave, "kindness")
    return (
        f"You are {name}, a beloved character from the children's picture book "
        f"'Myrtle and Ray and the First Day of Camp'. Role: {role}. "
        f"Your W.A.V.E. value: {wave_phrase}.\n\n"
        "A child has written you a letter. You must return TWO things in a single response:\n\n"
        "RHYME:\n"
        "Exactly 4 short rhyming couplets (8 lines total). 2nd-grade reading level. Warm, encouraging, "
        "referencing your W.A.V.E. value. Sign off with your name on its own last line. NO URLs, emails, phone "
        "numbers, scary topics. Stay in character.\n\n"
        "SCENE:\n"
        "On a single line, write 5 to 12 words describing what to DRAW for the child — a single playful "
        "beach/camp scene that fits your rhyme. Examples: 'Myrtle the Turtle flying a kite on the beach' or "
        "'Ray the Stingray and a friend building a sandcastle'. NO commas, no quotes, no period.\n\n"
        "Strict output format (use these exact labels):\n"
        "RHYME:\n"
        "<8 lines>\n\n"
        "SCENE:\n"
        "<one short phrase>"
    )


_RHYME_RE = re.compile(r"RHYME:\s*(.+?)\s*SCENE:\s*(.+)", re.DOTALL | re.IGNORECASE)


def _parse_studio_response(raw: str, character_name: str) -> tuple[str, str]:
    """Returns (reply_text, scene_prompt). Falls back to safe defaults if the
    LLM ignored the format."""
    if not raw:
        return ("", "")
    m = _RHYME_RE.search(raw.strip())
    if not m:
        # Try a softer parse: split on "SCENE"
        parts = re.split(r"\n\s*SCENE\s*:\s*", raw, maxsplit=1, flags=re.I)
        if len(parts) == 2:
            rhyme = re.sub(r"^\s*RHYME\s*:\s*", "", parts[0], flags=re.I).strip()
            scene = parts[1].strip().splitlines()[0].strip().strip('"').strip(".") if parts[1].strip() else ""
            return (rhyme, scene)
        return (raw.strip(), f"{character_name} smiling at the beach")
    rhyme = m.group(1).strip()
    scene = m.group(2).strip().splitlines()[0].strip().strip('"').strip(".")
    return (rhyme, scene)


def make_seastar_studio_router(db, require_admin):
    router = APIRouter(tags=["seastar-studio"])

    async def _settings() -> dict:
        s = await db.studio_settings.find_one({"_id": "settings"}, {"_id": 0}) or {}
        return {
            "enabled": s.get("enabled", True),
            "daily_cap": int(s.get("daily_cap") or 3),
            "text_model": s.get("text_model") or "gemini-3-flash-preview",
            "image_model": s.get("image_model") or "gemini-3.1-flash-image-preview",
            "audio_enabled": bool(s.get("audio_enabled", True)),
        }

    # ---- Public ----

    @router.get("/sea-star-studio/settings")
    async def public_settings():
        s = await _settings()
        return {"enabled": s["enabled"], "daily_cap": s["daily_cap"]}

    @router.get("/sea-star-studio/history/{visitor_id}")
    async def history(visitor_id: str, limit: int = 12):
        cur = db.sea_star_keepsakes.find(
            {"visitor_id": visitor_id, "deleted": {"$ne": True}},
            {"_id": 0},
        ).sort("created_at", -1).limit(min(48, max(1, int(limit))))
        return await cur.to_list(48)

    @router.post("/sea-star-studio/create")
    async def create_keepsake(body: StudioBody):
        settings = await _settings()
        if not settings["enabled"]:
            raise HTTPException(status_code=503, detail="The Sea Star Studio is closed right now. Come back soon!")

        clean = sanitize_letter(body.letter)
        if not clean:
            raise HTTPException(status_code=400, detail="Write a sentence to your Sea Star!")
        if contains_banned(clean) or _is_blocked(clean):
            raise HTTPException(status_code=400, detail="Let's keep it kind and friendly — try again!")

        ch = await db.characters.find_one({"slug": body.character_slug}, {"_id": 0})
        if not ch:
            raise HTTPException(status_code=404, detail="That Sea Star isn't here.")

        # Rate limit per visitor per day
        used = await db.sea_star_keepsakes.count_documents({
            "visitor_id": body.visitor_id,
            "day_key": _today_key(),
        })
        if used >= settings["daily_cap"]:
            raise HTTPException(status_code=429, detail=f"You've made {used} keepsakes today — come back tomorrow!")

        # Cache key for the (character, letter) pair
        cache_key = hashlib.sha256(
            f"studio|{body.character_slug}|{clean.strip().lower()}".encode("utf-8")
        ).hexdigest()
        cached = await db.studio_cache.find_one({"key": cache_key}, {"_id": 0})

        if cached:
            reply_text = cached["reply_text"]
            scene_prompt = cached.get("scene_prompt", "")
            audio_url = cached.get("audio_url", "")
            image_url = cached.get("image_url", "")

            # Self-heal legacy cache rows whose audio_url points at a stale
            # MP3 (generated for a different reply_text under the old
            # cache_key-only filename scheme). Detect via the text-hash
            # fragment that should now appear in every audio URL.
            if (
                settings["audio_enabled"]
                and ch.get("voice_id")
                and reply_text
                and audio_url
            ):
                expected_fragment = _expected_audio_fragment(ch["voice_id"], reply_text)
                if expected_fragment and expected_fragment not in audio_url:
                    logger.info(
                        "Studio audio cache stale for key=%s — re-synthesizing",
                        cache_key,
                    )
                    try:
                        fresh = await _synthesize_audio(reply_text, ch["voice_id"], cache_key)
                        if fresh:
                            audio_url = fresh
                            await db.studio_cache.update_one(
                                {"key": cache_key},
                                {"$set": {"audio_url": fresh, "updated_at": _now_iso()}},
                            )
                    except Exception as exc:  # noqa: BLE001
                        logger.warning("Studio audio re-sync failed: %s", exc)

            # Symmetric defense for the coloring image: if the cached
            # image_url doesn't include the scene-hash fragment we'd
            # expect for the current scene_prompt, the PNG was generated
            # for a different scene — regenerate.
            if scene_prompt and image_url:
                expected_scene = _expected_image_fragment(scene_prompt)
                if expected_scene and expected_scene not in image_url:
                    logger.info(
                        "Studio image cache stale for key=%s — re-generating",
                        cache_key,
                    )
                    try:
                        fresh_img = await _generate_scene_image(
                            character_name=ch.get("name", ""),
                            character_role=ch.get("role", ""),
                            scene_prompt=scene_prompt,
                            image_model=settings["image_model"],
                            cache_key=cache_key,
                        )
                        if fresh_img:
                            image_url = fresh_img
                            await db.studio_cache.update_one(
                                {"key": cache_key},
                                {"$set": {"image_url": fresh_img, "updated_at": _now_iso()}},
                            )
                    except Exception as exc:  # noqa: BLE001
                        logger.warning("Studio image re-sync failed: %s", exc)
        else:
            # 1) ONE LLM call → rhyme + scene
            reply_text, scene_prompt = await _generate_rhyme_and_scene(
                ch=ch,
                child_letter=clean,
                child_name=(body.child_name or "").strip()[:30],
                model_name=settings["text_model"],
                cache_key=cache_key,
            )

            # 2) ElevenLabs audio (best-effort)
            audio_url = ""
            if settings["audio_enabled"] and ch.get("voice_id"):
                try:
                    audio_url = await _synthesize_audio(reply_text, ch["voice_id"], cache_key)
                except Exception as exc:  # noqa: BLE001
                    logger.warning("Studio audio failed: %s", exc)
                    audio_url = ""

            # 3) Coloring page from scene_prompt
            image_url = ""
            try:
                image_url = await _generate_scene_image(
                    character_name=ch.get("name", ""),
                    character_role=ch.get("role", ""),
                    scene_prompt=scene_prompt or f"{ch.get('name','')} at Stingray Cay",
                    image_model=settings["image_model"],
                    cache_key=cache_key,
                )
            except Exception as exc:  # noqa: BLE001
                logger.warning("Studio image failed: %s", exc)
                image_url = ""

            await db.studio_cache.insert_one({
                "key": cache_key,
                "character_slug": body.character_slug,
                "reply_text": reply_text,
                "scene_prompt": scene_prompt,
                "audio_url": audio_url,
                "image_url": image_url,
                "created_at": _now_iso(),
            })

        # Persist the keepsake
        doc = {
            "id": str(uuid.uuid4()),
            "visitor_id": body.visitor_id,
            "day_key": _today_key(),
            "character_slug": body.character_slug,
            "character_name": ch.get("name", ""),
            "letter": clean,
            "child_name": (body.child_name or "")[:30],
            "reply_text": reply_text,
            "scene_prompt": scene_prompt,
            "audio_url": audio_url,
            "image_url": image_url,
            "cache_key": cache_key,
            "deleted": False,
            "created_at": _now_iso(),
        }
        await db.sea_star_keepsakes.insert_one(dict(doc))
        doc.pop("_id", None)

        return {
            "id": doc["id"],
            "character_slug": body.character_slug,
            "character_name": ch.get("name", ""),
            "reply_text": reply_text,
            "scene_prompt": scene_prompt,
            "audio_url": audio_url,
            "image_url": image_url,
            "keepsakes_left_today": max(0, settings["daily_cap"] - used - 1),
        }

    # ---- Admin ----
    admin = APIRouter(prefix="/admin/sea-star-studio", tags=["admin-studio"], dependencies=[Depends(require_admin)])

    @admin.get("/settings")
    async def get_settings():
        return await _settings()

    @admin.put("/settings")
    async def update_settings(body: dict):
        patch = {k: v for k, v in (body or {}).items() if k in {"enabled", "daily_cap", "text_model", "image_model", "audio_enabled"}}
        patch["updated_at"] = _now_iso()
        await db.studio_settings.update_one({"_id": "settings"}, {"$set": patch}, upsert=True)
        return await _settings()

    @admin.get("/keepsakes")
    async def list_keepsakes(limit: int = 100, character: str = "", search: str = ""):
        q: dict = {}
        if character:
            q["character_slug"] = character
        if search:
            q["$or"] = [{"letter": {"$regex": search, "$options": "i"}}, {"reply_text": {"$regex": search, "$options": "i"}}]
        cur = db.sea_star_keepsakes.find(q, {"_id": 0}).sort("created_at", -1).limit(min(500, max(1, int(limit))))
        rows = await cur.to_list(500)
        total = await db.sea_star_keepsakes.count_documents({})
        today = await db.sea_star_keepsakes.count_documents({"day_key": _today_key()})
        return {"keepsakes": rows, "total": total, "today": today}

    @admin.delete("/keepsakes/{kid}")
    async def delete_keepsake(kid: str):
        res = await db.sea_star_keepsakes.update_one({"id": kid}, {"$set": {"deleted": True, "deleted_at": _now_iso()}})
        if res.matched_count == 0:
            raise HTTPException(status_code=404, detail="Keepsake not found.")
        return {"ok": True}

    router.include_router(admin)
    return router


# ---------------- LLM helpers ----------------

async def _generate_rhyme_and_scene(ch: dict, child_letter: str, child_name: str,
                                    model_name: str, cache_key: str) -> tuple[str, str]:
    """One Gemini Flash call returns both the rhyme AND the scene prompt.
    Falls back to a canned reply + generic scene if the LLM is unavailable."""
    api_key = (os.environ.get("EMERGENT_LLM_KEY") or "").strip()
    if not api_key:
        return (_fallback_reply(ch, child_name), f"{ch.get('name','')} at Stingray Cay")
    try:
        from emergentintegrations.llm.chat import LlmChat, UserMessage
    except Exception:  # noqa: BLE001
        return (_fallback_reply(ch, child_name), f"{ch.get('name','')} at Stingray Cay")

    sys_msg = _studio_system_prompt(ch)
    user_text = (
        f"My name is {child_name}.\n\n"
        if child_name else ""
    ) + f"Here is my letter to you:\n\n{child_letter}\n\nPlease write back AND tell me what scene to draw."

    try:
        chat = LlmChat(api_key=api_key, session_id=f"studio-{cache_key[:12]}", system_message=sys_msg) \
            .with_model("gemini", model_name or "gemini-3-flash-preview")
        raw = await chat.send_message(UserMessage(text=user_text))
        reply_text, scene_prompt = _parse_studio_response(raw or "", ch.get("name", ""))
        if not reply_text:
            reply_text = _fallback_reply(ch, child_name)
        if not scene_prompt:
            scene_prompt = f"{ch.get('name','')} smiling at the beach"
        return (reply_text[:2000], scene_prompt[:200])
    except Exception as exc:  # noqa: BLE001
        logger.warning("Studio LLM failed (%s) — fallback", exc)
        return (_fallback_reply(ch, child_name), f"{ch.get('name','')} at Stingray Cay")


def _expected_image_fragment(scene_prompt: str) -> str:
    """Returns the scene-hash suffix that should appear in the coloring
    image URL for the given scene_prompt. Used to detect stale legacy
    cache rows whose image PNG was generated for a different scene."""
    if not scene_prompt:
        return ""
    return hashlib.sha256(scene_prompt.strip().lower().encode("utf-8")).hexdigest()[:16]


async def _generate_scene_image(character_name: str, character_role: str, scene_prompt: str,
                                image_model: str, cache_key: str) -> str:
    """Generate the coloring-book PNG for the LLM-chosen scene. Writes
    /app/backend/uploads/coloring/<cache_key>_<scene_hash>.png so the on-disk
    file is uniquely identified by its scene content — prevents the
    'stale image' counterpart of the audio bug fixed earlier."""
    api_key = (os.environ.get("EMERGENT_LLM_KEY") or "").strip()
    if not api_key:
        return ""
    try:
        from emergentintegrations.llm.chat import LlmChat, UserMessage
    except Exception:  # noqa: BLE001
        return ""

    scene_hash = _expected_image_fragment(scene_prompt)
    fname = f"{cache_key}_{scene_hash}.png" if scene_hash else f"{cache_key}.png"
    local_path = os.path.join(COLORING_DIR, fname)
    url_path = f"/api/uploads/coloring/{fname}"
    if os.path.exists(local_path):
        return url_path

    sys_msg = coloring_system_prompt(character_name, character_role)
    user_text = (
        f"Create a coloring-book line-art page of {character_name} {scene_prompt}. "
        "No colors, no shading, no gray, no text, no signature, no watermark, white background."
    )
    chat = LlmChat(api_key=api_key, session_id=f"studio-img-{cache_key[:12]}", system_message=sys_msg) \
        .with_model("gemini", image_model or "gemini-3.1-flash-image-preview").with_params(modalities=["image", "text"])

    _text, images = await chat.send_message_multimodal_response(UserMessage(text=user_text))
    if not images:
        return ""
    img = images[0]
    data_b64 = img.get("data") if isinstance(img, dict) else None
    if not data_b64:
        return ""
    image_bytes = base64.b64decode(data_b64)
    with open(local_path, "wb") as fh:
        fh.write(image_bytes)
    # Push to persistent storage
    try:
        import storage as _storage
        if _storage.is_enabled():
            _storage.put_object(f"coloring/{fname}", image_bytes, "image/png")
    except Exception:  # noqa: BLE001
        pass
    return url_path
